services:
  db:
    image: mysql:8.0
    container_name: geofence_mysql
    restart: always
    environment:
      MYSQL_DATABASE: geofence_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: geo_user
      MYSQL_PASSWORD: geopassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: ./backend
    container_name: geofence_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  mysql_data: