services:
  db:
    image: mysql:8.0
    container_name: geofence_mysql
    restart: always
    environment:
      MYSQL_DATABASE: geofence_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: geo_user
      MYSQL_PASSWORD: geopassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: